PL/Controllers/Producto1Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class Producto1Controller : Controller
    {
        private readonly IConfiguration _configuration;

        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment _hostingEnvironment;

        public Producto1Controller(IConfiguration configuration, Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnvironment)
        {
            _configuration = configuration;
            _hostingEnvironment = hostingEnvironment;
        }
        [HttpGet]
        public ActionResult GetAll()
        {

            ML.Producto producto = new ML.Producto();
            producto.Departamento = new ML.Departamento();
            producto.Proveedor = new ML.Proveedor();
            ML.Result result = new ML.Result();

            ML.Result resultDepartamento = new ML.Result();
            ML.Result resultProveedor= new ML.Result();

            resultDepartamento = BL.Departamento.GetAll();
            resultProveedor = BL.Proveedor.GetAll();

            try
            {
                string urlAPI = _configuration["UrlAPI"];
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(urlAPI);

                    var responseTask = client.GetAsync("Producto/GetAll");


                    responseTask.Wait();

                    var resultServicio = responseTask.Result;

                    if (resultServicio.IsSuccessStatusCode)
                    {
                        var readTask = resultServicio.Content.ReadAsAsync<ML.Result>();
                        readTask.Wait();
                        result.Objects = new List<object>();
                        foreach (var resultItem in readTask.Result.Objects)
                        {
                            ML.Producto resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Producto>(resultItem.ToString());
                            result.Objects.Add(resultItemList);
                        }

                        result.Correct = true;
                    }
                    else
                    {
                        result.Correct = false;
                    }
                }
                if (result.Correct == true)
                {
                    producto.Productos = result.Objects;
                    producto.Proveedor.Proveedores = resultProveedor.Objects;
                    producto.Departamento.Departamentos = resultDepartamento.Objects;
                }
                else
                {
                    ViewBag.Message = "OCURRÓ EL SIGUIENTE ERROR " + result.ErrorMessage;
                }

            }
            catch (Exception ex)
            {
                result.Correct = false;
                result.ErrorMessage = ex.Message;
            }

            return View(producto);
        }
        [HttpGet]
        public ActionResult Form(int? IdProducto)
        {

            ML.Producto producto = new ML.Producto();
            producto.Departamento = new ML.Departamento();
            producto.Proveedor = new ML.Proveedor();
            ML.Result result = new ML.Result();

            ML.Result resultDepartamento = new ML.Result();
            ML.Result resultProveedor = new ML.Result();

            resultDepartamento = BL.Departamento.GetAll();
            resultProveedor = BL.Proveedor.GetAll();

            try
            {
                string urlAPI = _configuration["UrlAPI"];
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(urlAPI);

                    var responseTask = client.GetAsync(("Producto/GetById/" + IdProducto.Value));


                    responseTask.Wait();

                    var resultServicio = responseTask.Result;

                    if (resultServicio.IsSuccessStatusCode)
                    {
                        var readTask = resultServicio.Content.ReadAsAsync<ML.Producto>();
                        readTask.Wait();
                        result.Object = readTask.Result;


                        result.Correct = true;
                    }
                    else
                    {
                        result.Correct = false;
                    }
                }

                if (result.Correct == true)
                {

                    producto = (ML.Producto)result.Object;

                }
                else
                {
                    ViewBag.Message = "Ocurrio el siguiente error: " + result.ErrorMessage;
                }


            }
            catch (Exception ex)
            {
                result.Correct = false;
                result.ErrorMessage = ex.Message;

            }
            producto.Productos = result.Objects;
            producto.Proveedor.Proveedores = resultProveedor.Objects;
            producto.Departamento.Departamentos = resultDepartamento.Objects;
            return View(producto);

        }

        [HttpPost]
        public ActionResult Form(ML.Producto producto)
        {
            ML.Result result = new ML.Result();
            IFormFile image = Request.Form.Files["ImagenData"];



            if (image != null)
            {

                byte[] ImagenBytes = ConvertToBytes(image);

                producto.Imagen = Convert.ToBase64String(ImagenBytes);
            }

            if (ModelState.IsValid == true)
            {
                if (producto.IdProducto == 0)
                {
                    try
                    {
                        string urlAPI = _configuration["UrlAPI"];
                        using (var client = new HttpClient())
                        {
                            client.BaseAddress = new Uri(urlAPI);

                            var responseTask = client.PostAsJsonAsync<ML.Producto>("Producto/Add", producto);


                            responseTask.Wait();

                            var resultServicio = responseTask.Result;

                            if (resultServicio.IsSuccessStatusCode)
                            {

                                result.Correct = true;
                            }
                            else
                            {
                                result.Correct = false;
                            }
                        }
                        if (result.Correct == true)
                        {
                            ViewBag.Message = "El Producto Se ha Registrado Con Exito";
                        }
                        else
                        {
                            ViewBag.Message = "El Producto No Se ha Registrado Con Exito";
                        }

                    }
                    catch (Exception ex)
                    {
                        result.Correct = false;
                        result.ErrorMessage = ex.Message;
                    }

                }
                else
                {
                    try
                    {
                        string urlAPI = _configuration["UrlAPI"];
                        using (var client = new HttpClient())
                        {
                            client.BaseAddress = new Uri(urlAPI);

                            var responseTask = client.PostAsJsonAsync<ML.Producto>("Producto/Update", producto);


                            responseTask.Wait();

                            var resultServicio = responseTask.Result;

                            if (resultServicio.IsSuccessStatusCode)
                            {

                                result.Correct = true;
                            }
                            else
                            {
                                result.Correct = false;
                            }
                        }
                        if (result.Correct == true)
                        {
                            ViewBag.Message = "El Producto Se ha Actualizado Con Exito";
                        }
                        else
                        {
                            ViewBag.Message = "El Producto No Se ha Actualizado Con Exito";
                        }

                    }
                    catch (Exception ex)
                    {
                        result.Correct = false;
                        result.ErrorMessage = ex.Message;
                    }

                }
                return PartialView("Modal");
            }
            else
            {
                ML.Result resultDepartamento = new ML.Result();
                ML.Result resultProveedor = new ML.Result();

                producto.Productos = result.Objects;
                producto.Proveedor.Proveedores = resultProveedor.Objects;
                producto.Departamento.Departamentos = resultDepartamento.Objects;
                return View(producto);

            }

        }

        [HttpGet]
        public ActionResult Delete(int IdProducto)
        {
            ML.Result result = new ML.Result();
            ML.Producto producto = new ML.Producto();
            if (IdProducto == 0)
            {
                ViewBag.Message = "Ocurrió un Error Al Eliminar";
            }
            else
            {
                string urlAPI = _configuration["UrlAPI"];
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(urlAPI);

                    var responseTask = client.GetAsync(("Producto/Delete/" + IdProducto));


                    responseTask.Wait();

                    var resultServicio = responseTask.Result;

                    if (resultServicio.IsSuccessStatusCode)
                    {
                        var readTask = resultServicio.Content.ReadAsAsync<ML.Producto>();
                        readTask.Wait();
                        result.Object = readTask.Result;

PL/Views/Producto1/Form.cshtml
@model ML.Producto
@{
    ViewBag.Title = "Form";
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Form</h2>
    <div class="row gx-5 justify-content-center">

        <div class="col-md-12">

            @using (Html.BeginForm("Form", "Producto1", FormMethod.Post, new { enctype = "multipart/form-data", @id="Hola" }))
            {
                <div class="form-horizontal container">

                    <div class="form-group row ">
                        <div class="col-md-3 visually-hidden">
                            @Html.LabelFor(model => model.IdProducto, new { @class = "hidden" })
                            @Html.TextBoxFor(model => model.IdProducto, new { @class = "hidden form-control" })
                            @Html.ValidationMessageFor(model => model.IdProducto)

                        </div>
                    

                    
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.NombreProducto)
                            <div class="input-group mb-3">
                                <span class="input-group-text"><i class="bi bi-controller"></i></span>
                                @Html.TextBoxFor(model => model.NombreProducto, new { @class = "form-control", @id = "txtNombre", @onkeypress = "return SoloLetras(event,'error')" })
                                

                                @Html.ValidationMessageFor(model => model.NombreProducto)
                            </div>
                            <label class="form-check-label" id="error"></label>
                        </div>
                                              

                    
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.PrecioUnitario)
                            <div class="input-group mb-3">
                                <span class="input-group-text"><i class="bi bi-controller"></i></span>

                                @Html.TextBoxFor(model => model.PrecioUnitario, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.PrecioUnitario)
                            </div>
                            <label class="form-check-label" id="error2"></label>

                        </div>
                    

                    
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Descripcion)
                            <div class="input-group mb-3">
                                <span class="input-group-text"><i class="bi bi-controller"></i></span>

                                @Html.TextBoxFor(model => model.Descripcion, new { @class = "form-control", @id = "txtDescripcion", @onkeypress = "return SoloLetras(event,'error3')" })
                                @Html.ValidationMessageFor(model => model.Descripcion)
                            </div>
                            <label class="form-check-label" id="error3" hidden></label>
                        </div>
                    

                    
                     
                    
                        
                    

                    
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Stock)
                            <div class="input-group mb-3">
                                <span class="input-group-text"><i class="bi bi-controller"></i></span>

                                @Html.TextBoxFor(model => model.Stock, new { @class = "form-control", @id = "txtNumeroDeTelefono", @onkeypress = "return SoloNumeros(event,'error5')" })
                                @Html.ValidationMessageFor(model => model.Stock)
                            </div>
                            <label class="form-check-label" id="error5"></label>

                        </div>
                    


                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Departamento.NombreDepartamento)
                            <div class="input-group mb-3">
                                                
                                <span class="input-group-text"><i class="bi bi-controller"></i></span>

                          
                                    @Html.DropDownListFor(model => model.Departamento.IdDepartamento, new SelectList(Model.Departamento.Departamentos, "IdDepartamento", "NombreDepartamento"), "Selecciona una opción", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Departamento.IdDepartamento)
                                
                            </div>
                        </div>
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Proveedor.NombreProveedor)
                            <div class="input-group mb-3">
                                                
                                <span class="input-group-text"><i class="bi bi-controller"></i></span>

                                    @Html.DropDownListFor(model => model.Proveedor.IdProveedor, new SelectList(Model.Proveedor.Proveedores, "IdProveedor", "NombreProveedor"), "Selecciona una opción", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Proveedor.IdProveedor)
                                
                            </div>
                        </div>


                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Imagen)
                             <div class="input-group mb-3">
                                <span class="input-group-text" id="basic-addon1"><i class="bi bi-card-image"></i></span>
                                <input accept="image/jpeg" type="file" name="ImagenData" class="form-control" onchange="readURL(this);" />
                            </div>
                            @if (Model.Imagen != null)
                            {
                                <img id="ImagenPreview" src="data:image/jpeg;base64,@Model.Imagen" style="height: 150px; width: 150px;" />
                            }
                            else
                            {
                                <img id="ImagenPreview" src="~/UsuarioSinFoto.png" style="height: 150px; width: 150px;"/>
                            }
                            @Html.ValidationMessageFor(model => model.Imagen)
                        </div>
                        @Html.HiddenFor(model => model.Imagen)

                    </div>

                    <hr />
                    <hr />
                    


                    <div class="form-group container row">
                        <div class="row">
                    
                            <div class="col-sm-4">
                            <input type="submit" value="Guardar" class="btn btn-success" />
                            @Html.ActionLink("Regresar", "GetAll", "Producto1", htmlAttributes: new { @class = "btn btn-danger" })
                            </div>
                        </div>
                    </div>
                   

                </div>
            }

        </div>
    </div>
</div>

@section Scripts
{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>

<script type="text/javascript">

    function readURL(input)
    {
        if (input.files && input.files[0])
        {
            var reader = new FileReader();
            reader.onload = function (e)
            {
                $('#ImagenPreview').attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }

        $(function () 
        {
            $("#txtFechaDeNacimiento").datepicker
            ({
                dateFormat: 'dd-mm-yy',
                changeMonth: true,
                yearRange: '1940:2004',
                changeYear: true
            });
        });

        function SoloNumeros(e, controlId) 
        {
            var caracter = e.key;
            if (!/^[0-9]/g.test(caracter)) 
            {
                $('#' + controlId).html("Solo se aceptan numeros");
                $('#' + controlId).css({ "color": "red" });
                return false;
            }
            else 
            {
                $('#' + controlId).text("");
                return true;
            }
        }

        function SoloLetras(e, controlId) 
        {
            var caracter = e.key;
            if (!/^[a-zA-Z ]/g.test(caracter)) {
                $('#' + controlId).html("Solo se aceptan letras");
                $('#' + controlId).css({ "color": "red" });
                return false;
            }
            else {
                $('#' + controlId).text("");
                return true;
            }
        }

        

</script>
}

PL/Views/Producto1/GetAll.cshtml
@model ML.Producto
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
   
}
<div class="container">
    <h2>GetAll</h2>
    <p></p>

    <div class="row justify-content-end">
        <div class="col-md-5 justify-content-end">
            @Html.ActionLink("Añadir Producto", "Form", "Producto1", htmlAttributes: new { @class = "btn btn-success col-md-5 justify-content-end" })
            
        </div>
    </div>
    <br />
    
    <hr />
    <hr />
    <div class="row d-flex justify-content-center table-responsive">
        <table class="table table-dark table-hover table-striped table-bordered" id="tblProveedor">

            <thead class="thead thead-inverse">
                <tr class="table table-secondary">

                    <th> EDITAR </th>
                    
                    <th align="center">NOMBRE </th>
                    <th align="center">PRECIO </th>
                    <th align="center">STOCK </th>
                    <th align="center">PROVEEDOR </th>
                    <th align="center">DEPARTAMENTO </th>
                    
                    <th align="center"> DESCRIPCION</th>
                    
                    <th align="center">IMAGEN</th>

                    <th> ELIMINAR </th>
                </tr>
            </thead>

            <tbody>
                @foreach (ML.Producto producto in Model.Productos)
                {

                    <tr>
                        <td class="text-center"><a class="btn btn-warning bi bi-pencil-square" href="@Url.Action("Form", "Producto1", new { IdProducto = producto.IdProducto})"></a></td>

                        
                        <td align="center">@producto.NombreProducto</td>
                        <td align="center">@producto.PrecioUnitario</td>
                        <td align="center">@producto.Stock</td>
                        <td align="center">@producto.Proveedor.NombreProveedor</td>
                        <td align="center">@producto.Departamento.NombreDepartamento</td>
                        <td align="center">@producto.Descripcion</td>
                        
                      
                        @if (producto.Imagen != null)
                        {
                            <td align="center"><img src="data:image/jpeg;base64,@producto.Imagen" style="height: 150px; width: 150px" /></td>
                        }
                        else
                        {
                            <td align="center"><img src="~/UsuarioSinFoto.png" style="height: 150px; width: 150px;" /></td>
                        }
                        <td class="text-center"><a class="btn btn-danger bi bi-trash" href="@Url.Action("Delete", "Producto1", new { IdProducto = producto.IdProducto })" onclick="return confirm('¿Estas seguro que deseas eliminar este registro?');" type="submit"></a></td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

@section Scripts
{
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#tblProveedor').DataTable({
                searching: false,
                
                "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
                
                columnDefs: [
                    {
                        targets: ['_all'],
                        className: 'mdc-data-table__cell',
                    },
                ],
                language: {
                    url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
                },
            });
        });
        
    </script>
}

PL/Views/Producto1/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Producto1", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>