PL/Controllers/Proveedor1Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class Proveedor1Controller : Controller
    {
        private readonly IConfiguration _configuration;

        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment _hostingEnvironment;

        public Proveedor1Controller(IConfiguration configuration, Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnvironment)
        {
            _configuration = configuration;
            _hostingEnvironment = hostingEnvironment;
        }
        
        [HttpGet]
        public ActionResult GetAll()
        {

            ML.Proveedor proveedor = new ML.Proveedor();
            
            ML.Result result = new ML.Result();


            try
            {
                string urlAPI = _configuration["UrlAPI"];
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(urlAPI);

                    var responseTask = client.GetAsync("Proveedor/GetAll");


                    responseTask.Wait();

                    var resultServicio = responseTask.Result;

                    if (resultServicio.IsSuccessStatusCode)
                    {
                        var readTask = resultServicio.Content.ReadAsAsync<ML.Result>();
                        readTask.Wait();
                        result.Objects = new List<object>();
                        foreach (var resultItem in readTask.Result.Objects)
                        {
                            ML.Proveedor resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Proveedor>(resultItem.ToString());
                            result.Objects.Add(resultItemList);
                        }

                        result.Correct = true;
                    }
                    else
                    {
                        result.Correct = false;
                    }
                }
                if (result.Correct == true)
                {
                    proveedor.Proveedores = result.Objects;
                    
                }
                else
                {
                    ViewBag.Message = "OCURRÓ EL SIGUIENTE ERROR " + result.ErrorMessage;
                }

            }
            catch (Exception ex)
            {
                result.Correct = false;
                result.ErrorMessage = ex.Message;
            }

            return View(proveedor);
        }
        [HttpGet]
        public ActionResult Form(int? IdProveedor)
        {

            ML.Result result = new ML.Result();
            ML.Proveedor proveedor = new ML.Proveedor();
            try
            {
                string urlAPI = _configuration["UrlAPI"];
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(urlAPI);

                    var responseTask = client.GetAsync(("Proveedor/GetById/" + IdProveedor.Value));


                    responseTask.Wait();

                    var resultServicio = responseTask.Result;

                    if (resultServicio.IsSuccessStatusCode)
                    {
                        var readTask = resultServicio.Content.ReadAsAsync<ML.Proveedor>();
                        readTask.Wait();
                        result.Object = readTask.Result;


                        result.Correct = true;
                    }
                    else
                    {
                        result.Correct = false;
                    }
                }

                if (result.Correct == true)
                {

                    proveedor = (ML.Proveedor)result.Object;

                }
                else
                {
                    ViewBag.Message = "Ocurrio el siguiente error: " + result.ErrorMessage;
                }


            }
            catch (Exception ex)
            {
                result.Correct = false;
                result.ErrorMessage = ex.Message;

            }
            

            return View(proveedor);

        }

        [HttpPost]
        public ActionResult Form(ML.Proveedor proveedor)
        {
            ML.Result result = new ML.Result();
            IFormFile image = Request.Form.Files["ImagenData"];



            if (image != null)
            {

                byte[] ImagenBytes = ConvertToBytes(image);

                proveedor.Imagen = Convert.ToBase64String(ImagenBytes);
            }

            if (ModelState.IsValid == true)
            {
                if (proveedor.IdProveedor == 0)
                {
                    try
                    {
                        string urlAPI = _configuration["UrlAPI"];
                        using (var client = new HttpClient())
                        {
                            client.BaseAddress = new Uri(urlAPI);

                            var responseTask = client.PostAsJsonAsync<ML.Proveedor>("Proveedor/Add", proveedor);


                            responseTask.Wait();

                            var resultServicio = responseTask.Result;

                            if (resultServicio.IsSuccessStatusCode)
                            {

                                result.Correct = true;
                            }
                            else
                            {
                                result.Correct = false;
                            }
                        }
                        if (result.Correct == true)
                        {
                            ViewBag.Message = "El Proveedor Se ha Registrado Con Exito";
                        }
                        else
                        {
                            ViewBag.Message = "El Proveedor No Se ha Registrado Con Exito";
                        }

                    }
                    catch (Exception ex)
                    {
                        result.Correct = false;
                        result.ErrorMessage = ex.Message;
                    }

                }
                else
                {
                    try
                    {
                        string urlAPI = _configuration["UrlAPI"];
                        using (var client = new HttpClient())
                        {
                            client.BaseAddress = new Uri(urlAPI);

                            var responseTask = client.PostAsJsonAsync<ML.Proveedor>("Proveedor/Update", proveedor);


                            responseTask.Wait();

                            var resultServicio = responseTask.Result;

                            if (resultServicio.IsSuccessStatusCode)
                            {

                                result.Correct = true;
                            }
                            else
                            {
                                result.Correct = false;
                            }
                        }
                        if (result.Correct == true)
                        {
                            ViewBag.Message = "El Proveedor Se ha Actualizado Con Exito";
                        }
                        else
                        {
                            ViewBag.Message = "El Proveedor No Se ha Actualizado Con Exito";
                        }

                    }
                    catch (Exception ex)
                    {
                        result.Correct = false;
                        result.ErrorMessage = ex.Message;
                    }

                }
                return PartialView("Modal");
            }
            else
            {
                ML.Result resultRoles = new ML.Result();



                
                return View(proveedor);

            }

        }

        [HttpGet]
        public ActionResult Delete(int IdProveedor)
        {
            ML.Result result = new ML.Result();
            ML.Proveedor proveedor = new ML.Proveedor();
            if (IdProveedor == 0)
            {
                ViewBag.Message = "Ocurrió un Error Al Eliminar";
            }
            else
            {
                proveedor.IdProveedor = IdProveedor;
                result = BL.Proveedor.Delete(proveedor);
                if (result.Correct == true)
                {
                    ViewBag.Message = "El Proveedor Se ha Eliminado Con Exito";
                }
                else
                {
                    ViewBag.Message = "El Proveedor No Se ha Eliminado Con Exito";
                }
            }
            return PartialView("Modal");
        }
        public static byte[] ConvertToBytes(IFormFile Imagen)
        {
            using var fileStream = Imagen.OpenReadStream();

            byte[] datos = new byte[fileStream.Length];
            fileStream.Read(datos, 0, (int)fileStream.Length);

            return datos;
        }
    }
}

PL/Views/Proveedor1/Form.cshtml
@model ML.Proveedor
@{
    ViewBag.Title = "Form";
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Form</h2>
    <div class="row gx-5 justify-content-center">

        <div class="col-md-12">

            @using (Html.BeginForm("Form", "Proveedor1", FormMethod.Post, new { enctype = "multipart/form-data", @id="Hola" }))
            {
                <div class="form-horizontal container">

                    <div class="form-group row ">
                        <div class="col-md-3 visually-hidden">
                            @Html.LabelFor(model => model.IdProveedor, new { @class = "hidden" })
                            @Html.TextBoxFor(model => model.IdProveedor, new { @class = "hidden form-control" })
                            @Html.ValidationMessageFor(model => model.IdProveedor)

                        </div>
                    

                    
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.NombreProveedor)
                            <div class="input-group mb-3">
                                <span class="input-group-text"><i class="bi bi-controller"></i></span>
                                @Html.TextBoxFor(model => model.NombreProveedor, new { @class = "form-control", @id = "txtNombre", @onkeypress = "return SoloLetras(event,'error')" })
                                

                                @Html.ValidationMessageFor(model => model.IdProveedor)
                            </div>
                            <label class="form-check-label" id="error"></label>
                        </div>
                                              

                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Telefono)
                            <div class="input-group mb-3">
                                <span class="input-group-text"><i class="bi bi-controller"></i></span>

                                @Html.TextBoxFor(model => model.Telefono, new { @class = "form-control", @id = "txtNumeroDeTelefono", @onkeypress = "return SoloNumeros(event,'error5')" })
                                @Html.ValidationMessageFor(model => model.Telefono)
                            </div>
                            <label class="form-check-label" id="error5"></label>

                        </div>
                    




                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Imagen)
                             <div class="input-group mb-3">
                                <span class="input-group-text" id="basic-addon1"><i class="bi bi-card-image"></i></span>
                                <input accept="image/jpeg" type="file" name="ImagenData" class="form-control" onchange="readURL(this);" />
                            </div>
                            @if (Model.Imagen != null)
                            {
                                <img id="ImagenPreview" src="data:image/jpeg;base64,@Model.Imagen" style="height: 150px; width: 150px;" />
                            }
                            else
                            {
                                <img id="ImagenPreview" src="~/UsuarioSinFoto.png" style="height: 150px; width: 150px;"/>
                            }
                            @Html.ValidationMessageFor(model => model.Imagen)
                        </div>
                        @Html.HiddenFor(model => model.Imagen)

                    </div>

                    <hr />
                    <hr />
                    


                    <div class="form-group container row">
                        <div class="row">
                    
                            <div class="col-sm-4">
                            <input type="submit" value="Guardar" class="btn btn-success" />
                            @Html.ActionLink("Regresar", "GetAll", "Proveedor1", htmlAttributes: new { @class = "btn btn-danger" })
                            </div>
                        </div>
                    </div>
                   

                </div>
            }

        </div>
    </div>
</div>

@section Scripts
{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>

<script type="text/javascript">

    function readURL(input)
    {
        if (input.files && input.files[0])
        {
            var reader = new FileReader();
            reader.onload = function (e)
            {
                $('#ImagenPreview').attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }

        $(function () 
        {
            $("#txtFechaDeNacimiento").datepicker
            ({
                dateFormat: 'dd-mm-yy',
                changeMonth: true,
                yearRange: '1940:2004',
                changeYear: true
            });
        });

        function SoloNumeros(e, controlId) 
        {
            var caracter = e.key;
            if (!/^[0-9]/g.test(caracter)) 
            {
                $('#' + controlId).html("Solo se aceptan numeros");
                $('#' + controlId).css({ "color": "red" });
                return false;
            }
            else 
            {
                $('#' + controlId).text("");
                return true;
            }
        }

        function SoloLetras(e, controlId) 
        {
            var caracter = e.key;
            if (!/^[a-zA-Z ]/g.test(caracter)) {
                $('#' + controlId).html("Solo se aceptan letras");
                $('#' + controlId).css({ "color": "red" });
                return false;
            }
            else {
                $('#' + controlId).text("");
                return true;
            }
        }

        

</script>
}

PL/Views/Proveedor1/GetAll.cshtml
@model ML.Proveedor
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
   
}
<div class="container">
    <h2>GetAll</h2>
    <p></p>

    <div class="row justify-content-end">
        <div class="col-md-5 justify-content-end">
            @Html.ActionLink("Añadir Proveedor", "Form", "Proveedor", htmlAttributes: new { @class = "btn btn-success col-md-5 justify-content-end" })
            
        </div>
    </div>
    <br />
    
    <hr />
    <hr />
    <div class="row d-flex justify-content-center table-responsive">
        <table class="table table-dark table-hover table-striped table-bordered" id="tblProveedor">

            <thead class="thead thead-inverse">
                <tr class="table table-secondary">

                    <th> EDITAR </th>
                    
                    <th align="center">NOMBRE </th>
                    
                    <th align="center">NUMERO DE TELEFONO</th>
                    
                    <th align="center">IMAGEN</th>

                    <th> ELIMINAR </th>
                </tr>
            </thead>

            <tbody>
                @foreach (ML.Proveedor proveedor in Model.Proveedores)
                {

                    <tr>
                        <td class="text-center"><a class="btn btn-warning bi bi-pencil-square" href="@Url.Action("Form", "Proveedor1", new { IdProveedor = proveedor.IdProveedor})"></a></td>

                        
                        <td align="center">@proveedor.NombreProveedor</td>
                        
                        <td align="center">@proveedor.Telefono</td>
                        
                        
                        
                        @if (proveedor.Imagen != null)
                        {
                            <td align="center"><img src="data:image/jpeg;base64,@proveedor.Imagen" style="height: 150px; width: 150px" /></td>
                        }
                        else
                        {
                            <td align="center"><img src="~/UsuarioSinFoto.png" style="height: 150px; width: 150px;" /></td>
                        }
                        <td class="text-center"><a class="btn btn-danger bi bi-trash" href="@Url.Action("Delete", "Proveedor1", new { IdProveedor = proveedor.IdProveedor })" onclick="return confirm('¿Estas seguro que deseas eliminar este registro?');" type="submit"></a></td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

@section Scripts
{
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#tblProveedor').DataTable({
                searching: false,
                
                "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
                
                columnDefs: [
                    {
                        targets: ['_all'],
                        className: 'mdc-data-table__cell',
                    },
                ],
                language: {
                    url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
                },
            });
        });
        
    </script>
}

PL/Views/Proveedor1/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Proveedor1", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>